JUCE: juce_VST3Common.h File Reference
juce_VST3Common.h File Reference
Classes
class ComSmartPtr< ObjectType >
class MidiEventList
struct VST3BufferExchange< FloatType >
struct VST3FloatAndDoubleBusMapCompositeHelper< FloatType >
struct VST3FloatAndDoubleBusMapComposite
struct VST3FloatAndDoubleBusMapCompositeHelper< float >
struct VST3FloatAndDoubleBusMapCompositeHelper< double >
Macros
#define JUCE_DECLARE_VST3_COM_REF_METHODS
#define JUCE_DECLARE_VST3_COM_QUERY_METHODS
#define TEST_FOR_AND_RETURN_IF_VALID(iidToTest, ClassType)
#define TEST_FOR_COMMON_BASE_AND_RETURN_IF_VALID(iidToTest, CommonClassType, SourceClassType)
Functions
juce::String toString (const Steinberg::char8 *string) noexcept
juce::String toString (const Steinberg::char16 *string) noexcept
juce::String toString (const Steinberg::UString128 &string) noexcept
juce::String toString (const Steinberg::UString256 &string) noexcept
void toString128 (Steinberg::Vst::String128 result, const char *source)
void toString128 (Steinberg::Vst::String128 result, const juce::String &source)
Steinberg::Vst::TChar * toString (const juce::String &source) noexcept
Macro Definition Documentation
#define JUCE_DECLARE_VST3_COM_REF_METHODS
Value:
Steinberg::uint32 PLUGIN_API addRef() override   { return (Steinberg::uint32) ++refCount; } \
    Steinberg::uint32 PLUGIN_API release() override  { const int r = --refCount; if (r == 0) delete this; return (Steinberg::uint32) r; }
Referenced by MidiEventList::~MidiEventList().
#define JUCE_DECLARE_VST3_COM_QUERY_METHODS
Value:
Steinberg::tresult PLUGIN_API queryInterface (const Steinberg::TUID, void** obj) override \
    { \
        jassertfalse; \
        *obj = nullptr; \
        return Steinberg::kNotImplemented; \
    }
Referenced by MidiEventList::~MidiEventList().
#define TEST_FOR_AND_RETURN_IF_VALID (iidToTest, ClassType)
Value:
if (doUIDsMatch (iidToTest, ClassType::iid)) \
    { \
        addRef(); \
        *obj = dynamic_cast<ClassType*> (this); \
        return Steinberg::kResultOk; \
    }
#define TEST_FOR_COMMON_BASE_AND_RETURN_IF_VALID (iidToTest, CommonClassType, SourceClassType)
Value:
if (doUIDsMatch (iidToTest, CommonClassType::iid)) \
    { \
        addRef(); \
        *obj = (CommonClassType*) static_cast<SourceClassType*> (this); \
        return Steinberg::kResultOk; \
    }
Function Documentation
juce::String toString (const Steinberg::char8 * string) noexcept
Referenced by OSCAddressPattern::containsWildcards(), RecentlyOpenedFilesList::getAllFilenames(), Colour::getAlpha(), MACAddress::getBytes(), MemoryOutputStream::getDataSize(), RelativeCoordinate::getExpression(), MemoryBlock::getSize(), Time::toMilliseconds(), and toString().
juce::String toString (const Steinberg::char16 * string) noexcept
juce::String toString (const Steinberg::UString128 & string) noexcept
References toString().
juce::String toString (const Steinberg::UString256 & string) noexcept
References toString().
void toString128 (Steinberg::Vst::String128 result, const char * source)
void toString128 (Steinberg::Vst::String128 result, const juce::String & source)
Steinberg::Vst::TChar* toString (const juce::String & source) noexcept
References AudioChannelSet::addChannel(), AudioChannelSet::centre, AudioChannelSet::getChannelTypes(), jassert, jmin(), AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftRearSurround, AudioChannelSet::leftSurround, AudioChannelSet::mono(), AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightRearSurround, AudioChannelSet::rightSurround, AudioChannelSet::subbass, AudioChannelSet::subbass2, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, and AudioChannelSet::unknown.