JUCE: AudioProcessor::AudioBusArrangement Struct Reference
AudioProcessor::AudioBusArrangement Struct Reference
Represents a set of input and output buses for an AudioProcessor.
Public Member Functions
int getChannelIndexInProcessBlockBuffer (bool isInput, int busIndex, int channelIndex) const noexcept
Returns the position of a bus's channels within the processBlock buffer.
template<typename FloatType >
AudioBuffer< FloatType > getBusBuffer (AudioBuffer< FloatType > &processBlockBuffer, bool isInput, int busIndex) const
Returns an AudioBuffer containing a set of channel pointers for a specific bus.
int getTotalNumInputChannels () const noexcept
Returns the total number of channels in all the input buses.
int getTotalNumOutputChannels () const noexcept
Returns the total number of channels in all the output buses.
Public Attributes
Array< AudioProcessorBus > inputBuses
An array containing the list of input buses that this processor supports.
Array< AudioProcessorBus > outputBuses
An array containing the list of output buses that this processor supports.
Detailed Description
Represents a set of input and output buses for an AudioProcessor.
Member Function Documentation
int AudioProcessor::AudioBusArrangement::getChannelIndexInProcessBlockBuffer (bool isInput, int busIndex, int channelIndex) const noexcept
Returns the position of a bus's channels within the processBlock buffer.
This can be called in processBlock to figure out which channel of the master AudioSampleBuffer maps onto a specific bus's channel.
template<typename FloatType > AudioBuffer<FloatType> AudioProcessor::AudioBusArrangement::getBusBuffer (AudioBuffer< FloatType > & processBlockBuffer, bool isInput, int busIndex) const
Returns an AudioBuffer containing a set of channel pointers for a specific bus.
This can be called in processBlock to get a buffer containing a sub-group of the master AudioSampleBuffer which contains all the plugin channels.
References AudioBuffer< Type >::getArrayOfWritePointers(), and AudioBuffer< Type >::getNumSamples().
int AudioProcessor::AudioBusArrangement::getTotalNumInputChannels () const noexcept
Returns the total number of channels in all the input buses.
Referenced by AudioProcessor::getTotalNumInputChannels().
int AudioProcessor::AudioBusArrangement::getTotalNumOutputChannels () const noexcept
Returns the total number of channels in all the output buses.
Referenced by AudioProcessor::getTotalNumOutputChannels().
Member Data Documentation
Array<AudioProcessorBus> AudioProcessor::AudioBusArrangement::inputBuses
An array containing the list of input buses that this processor supports.
Referenced by StandalonePluginHolder::createPlugin(), AudioUnitHelpers::getAUChannelInfo(), PluginBusUtilities::getFilterBus(), and PluginBusUtilities::restoreBusArrangement().
Array<AudioProcessorBus> AudioProcessor::AudioBusArrangement::outputBuses
An array containing the list of output buses that this processor supports.
Referenced by AudioUnitHelpers::getAUChannelInfo(), PluginBusUtilities::getFilterBus(), and PluginBusUtilities::restoreBusArrangement().
The documentation for this struct was generated from the following file:
juce_AudioProcessor.h