JUCE: PluginBusUtilities Struct Reference
PluginBusUtilities Struct Reference
Classes
class ScopedBusRestorer
Public Types
enum { kDefaultMaxChannels = 64 }
typedef Array< AudioProcessor::AudioProcessorBus > AudioBusArray
Public Member Functions
PluginBusUtilities (AudioProcessor &plugin, bool markDiscreteLayoutsAsSupported, int maxProbeChannels=kDefaultMaxChannels)
void init ()
AudioBusArray & getFilterBus (bool inputBus) noexcept
const AudioBusArray & getFilterBus (bool inputBus) const noexcept
int getBusCount (bool inputBus) const noexcept
AudioChannelSet getChannelSet (bool inputBus, int bus) noexcept
int getNumChannels (bool inp, int bus) const noexcept
bool isBusEnabled (bool inputBus, int bus) const noexcept
bool hasInputs (int bus) const noexcept
bool hasOutputs (int bus) const noexcept
bool hasDynamicInBuses () const noexcept
bool hasDynamicOutBuses () const noexcept
int getNumEnabledBuses (bool inputBus) const noexcept
int findTotalNumChannels (bool isInput, int busOffset=0) const noexcept
int getBusIdxForChannelIdx (bool isInput, int channelIdx, int &totalChannels, int startBusIdx)
int getBusIdxForChannelIdx (bool isInput, int channelIdx)
bool busIgnoresLayout (bool inp, int bus) const noexcept
bool busCanBeDisabled (bool inp, int bus) const noexcept
bool isBusEnabledByDefault (bool inp, int bus) const noexcept
bool checkBusFormatsAreNotDiscrete () const
const AudioChannelSet & getDefaultLayoutForBus (bool isInput, int busIdx) const noexcept
AudioChannelSet getDefaultLayoutForChannelNumAndBus (bool isInput, int busIdx, int channelNum) const noexcept
int findMaxNumberOfChannelsForBus (bool isInput, int busNr, int upperlimit=std::numeric_limits< int >::max())
void restoreBusArrangement (const AudioProcessor::AudioBusArrangement &original) const
void enableAllBuses ()
Public Attributes
AudioProcessor & processor
Member Typedef Documentation
typedef Array<AudioProcessor::AudioProcessorBus> PluginBusUtilities::AudioBusArray
Member Enumeration Documentation
anonymous enum
Enumerator
kDefaultMaxChannels
Constructor & Destructor Documentation
PluginBusUtilities::PluginBusUtilities (AudioProcessor & plugin, bool markDiscreteLayoutsAsSupported, int maxProbeChannels = kDefaultMaxChannels)
Member Function Documentation
void PluginBusUtilities::init ()
AudioBusArray& PluginBusUtilities::getFilterBus (bool inputBus) noexcept
References AudioProcessor::busArrangement, AudioProcessor::AudioBusArrangement::inputBuses, AudioProcessor::AudioBusArrangement::outputBuses, and processor.
Referenced by findTotalNumChannels(), getBusCount(), getChannelSet(), and getNumChannels().
const AudioBusArray& PluginBusUtilities::getFilterBus (bool inputBus) const noexcept
References AudioProcessor::busArrangement, AudioProcessor::AudioBusArrangement::inputBuses, AudioProcessor::AudioBusArrangement::outputBuses, and processor.
int PluginBusUtilities::getBusCount (bool inputBus) const noexcept
References getFilterBus(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by enableAllBuses(), getBusIdxForChannelIdx(), getDefaultLayoutForChannelNumAndBus(), getNumChannels(), getNumEnabledBuses(), and restoreBusArrangement().
AudioChannelSet PluginBusUtilities::getChannelSet (bool inputBus, int bus) noexcept
References AudioProcessor::AudioProcessorBus::channels, getFilterBus(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference().
Referenced by enableAllBuses(), and AudioUnitHelpers::ChannelRemapper::get().
int PluginBusUtilities::getNumChannels (bool inp, int bus) const noexcept
References AudioProcessor::AudioProcessorBus::channels, getBusCount(), getFilterBus(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), isPositiveAndBelow(), and AudioChannelSet::size().
Referenced by AudioUnitHelpers::ChannelRemapper::get(), AudioUnitHelpers::getAUChannelInfo(), getBusIdxForChannelIdx(), and isBusEnabled().
bool PluginBusUtilities::isBusEnabled (bool inputBus, int bus) const noexcept
References getNumChannels().
Referenced by getNumEnabledBuses(), hasInputs(), and hasOutputs().
bool PluginBusUtilities::hasInputs (int bus) const noexcept
References isBusEnabled().
bool PluginBusUtilities::hasOutputs (int bus) const noexcept
References isBusEnabled().
bool PluginBusUtilities::hasDynamicInBuses () const noexcept
bool PluginBusUtilities::hasDynamicOutBuses () const noexcept
int PluginBusUtilities::getNumEnabledBuses (bool inputBus) const noexcept
References getBusCount(), and isBusEnabled().
Referenced by AudioUnitHelpers::getAUChannelInfo().
int PluginBusUtilities::findTotalNumChannels (bool isInput, int busOffset = 0) const noexcept
References AudioProcessor::AudioProcessorBus::channels, getFilterBus(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), AudioChannelSet::size(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by AudioUnitHelpers::ChannelRemapper::get().
int PluginBusUtilities::getBusIdxForChannelIdx (bool isInput, int channelIdx, int & totalChannels, int startBusIdx)
References getBusCount(), and getNumChannels().
Referenced by getBusIdxForChannelIdx().
int PluginBusUtilities::getBusIdxForChannelIdx (bool isInput, int channelIdx)
References getBusIdxForChannelIdx().
bool PluginBusUtilities::busIgnoresLayout (bool inp, int bus) const noexcept
References isPositiveAndBelow().
bool PluginBusUtilities::busCanBeDisabled (bool inp, int bus) const noexcept
References isPositiveAndBelow().
bool PluginBusUtilities::isBusEnabledByDefault (bool inp, int bus) const noexcept
References isPositiveAndBelow().
bool PluginBusUtilities::checkBusFormatsAreNotDiscrete () const
const AudioChannelSet& PluginBusUtilities::getDefaultLayoutForBus (bool isInput, int busIdx) const noexcept
Referenced by enableAllBuses().
AudioChannelSet PluginBusUtilities::getDefaultLayoutForChannelNumAndBus (bool isInput, int busIdx, int channelNum) const noexcept
References AudioChannelSet::disabled(), AudioChannelSet::discreteChannels(), getBusCount(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), AudioChannelSet::isDiscreteLayout(), processor, AudioProcessor::setPreferredBusArrangement(), AudioChannelSet::size(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by AudioUnitHelpers::getAUChannelInfo().
int PluginBusUtilities::findMaxNumberOfChannelsForBus (bool isInput, int busNr, int upperlimit = std::numeric_limits<int>::max())
References AudioChannelSet::discreteChannels(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), jmax(), jmin(), processor, AudioProcessor::setPreferredBusArrangement(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
void PluginBusUtilities::restoreBusArrangement (const AudioProcessor::AudioBusArrangement & original) const
References getBusCount(), AudioProcessor::AudioBusArrangement::inputBuses, jassert, AudioProcessor::AudioBusArrangement::outputBuses, processor, and AudioProcessor::setPreferredBusArrangement().
Referenced by PluginBusUtilities::ScopedBusRestorer::~ScopedBusRestorer().
void PluginBusUtilities::enableAllBuses ()
References AudioChannelSet::disabled(), getBusCount(), getChannelSet(), getDefaultLayoutForBus(), processor, and AudioProcessor::setPreferredBusArrangement().
Member Data Documentation
AudioProcessor& PluginBusUtilities::processor
Referenced by enableAllBuses(), findMaxNumberOfChannelsForBus(), AudioUnitHelpers::getAUChannelInfo(), getDefaultLayoutForChannelNumAndBus(), getFilterBus(), and restoreBusArrangement().
The documentation for this struct was generated from the following file:
juce_PluginBusUtilities.h