JUCE: AudioUnitHelpers Struct Reference
AudioUnitHelpers Struct Reference
Classes
struct AUChannelStreamOrder
class ChannelRemapper
class CoreAudioBufferList
Static Public Member Functions
static AudioChannelSet::ChannelType CoreAudioChannelLabelToJuceType (AudioChannelLabel label) noexcept
static AudioChannelLabel JuceChannelTypeToCoreAudioLabel (const AudioChannelSet::ChannelType &label) noexcept
static AudioChannelSet CoreAudioChannelBitmapToJuceType (UInt32 bitmap) noexcept
static AudioChannelSet CoreAudioChannelLayoutToJuceType (const AudioChannelLayout &layout) noexcept
static AudioChannelSet CALayoutTagToChannelSet (AudioChannelLayoutTag tag) noexcept
static AudioChannelLayoutTag ChannelSetToCALayoutTag (const AudioChannelSet &set) noexcept
static int auChannelIndexToJuce (int auIndex, const AudioChannelSet &channelSet)
static int juceChannelIndexToAu (int juceIndex, const AudioChannelSet &channelSet)
static bool isAudioBufferInterleaved (const AudioBufferList &audioBuffer) noexcept
static void clearAudioBuffer (const AudioBufferList &audioBuffer) noexcept
static void copyAudioBuffer (const AudioBufferList &audioBuffer, const int channel, const UInt32 size, float *dst) noexcept
static void copyAudioBuffer (const float *src, const int channel, const UInt32 size, AudioBufferList &audioBuffer) noexcept
static Array< AUChannelInfo > getAUChannelInfo (PluginBusUtilities &busUtils)
Static Public Attributes
static AUChannelStreamOrder auChannelStreamOrder []
Member Function Documentation
static AudioChannelSet::ChannelType AudioUnitHelpers::CoreAudioChannelLabelToJuceType (AudioChannelLabel label) static noexcept
References AudioChannelSet::ambisonicW, AudioChannelSet::ambisonicX, AudioChannelSet::ambisonicY, AudioChannelSet::ambisonicZ, AudioChannelSet::centre, AudioChannelSet::discreteChannel0, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftRearSurround, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundDirect, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightRearSurround, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundDirect, AudioChannelSet::subbass, AudioChannelSet::subbass2, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, AudioChannelSet::unknown, AudioChannelSet::wideLeft, and AudioChannelSet::wideRight.
Referenced by auChannelIndexToJuce(), CoreAudioChannelLayoutToJuceType(), and juceChannelIndexToAu().
static AudioChannelLabel AudioUnitHelpers::JuceChannelTypeToCoreAudioLabel (const AudioChannelSet::ChannelType & label) static noexcept
References AudioChannelSet::ambisonicW, AudioChannelSet::ambisonicX, AudioChannelSet::ambisonicY, AudioChannelSet::ambisonicZ, AudioChannelSet::centre, AudioChannelSet::discreteChannel0, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftRearSurround, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundDirect, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightRearSurround, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundDirect, AudioChannelSet::subbass, AudioChannelSet::subbass2, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, AudioChannelSet::unknown, AudioChannelSet::wideLeft, and AudioChannelSet::wideRight.
static AudioChannelSet AudioUnitHelpers::CoreAudioChannelBitmapToJuceType (UInt32 bitmap) static noexcept
References AudioChannelSet::addChannel(), AudioChannelSet::centre, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundDirect, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundDirect, AudioChannelSet::subbass, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, and AudioChannelSet::topRearRight.
Referenced by CoreAudioChannelLayoutToJuceType().
static AudioChannelSet AudioUnitHelpers::CoreAudioChannelLayoutToJuceType (const AudioChannelLayout & layout) static noexcept
References AudioUnitHelpers::AUChannelStreamOrder::auLayoutTag, CALayoutTagToChannelSet(), CoreAudioChannelBitmapToJuceType(), CoreAudioChannelLabelToJuceType(), and AudioUnitHelpers::AUChannelStreamOrder::speakerOrder.
static AudioChannelSet AudioUnitHelpers::CALayoutTagToChannelSet (AudioChannelLayoutTag tag) static noexcept
References AudioChannelSet::ambisonic(), AudioChannelSet::create5point0(), AudioChannelSet::create5point1(), AudioChannelSet::create6point0(), AudioChannelSet::create6point0Music(), AudioChannelSet::create6point1(), AudioChannelSet::create7point0(), AudioChannelSet::create7point1(), AudioChannelSet::create7point1AC3(), AudioChannelSet::createFront7point0(), AudioChannelSet::createFront7point1(), AudioChannelSet::createLCR(), AudioChannelSet::createLCRS(), AudioChannelSet::createLRS(), AudioChannelSet::disabled(), AudioChannelSet::discreteChannels(), AudioChannelSet::hexagonal(), jassertfalse, AudioChannelSet::mono(), AudioChannelSet::octagonal(), AudioChannelSet::pentagonal(), AudioChannelSet::quadraphonic(), and AudioChannelSet::stereo().
Referenced by CoreAudioChannelLayoutToJuceType().
static AudioChannelLayoutTag AudioUnitHelpers::ChannelSetToCALayoutTag (const AudioChannelSet & set) static noexcept
References AudioChannelSet::ambisonic(), AudioChannelSet::create5point0(), AudioChannelSet::create5point1(), AudioChannelSet::create6point0(), AudioChannelSet::create6point0Music(), AudioChannelSet::create6point1(), AudioChannelSet::create7point0(), AudioChannelSet::create7point1(), AudioChannelSet::create7point1AC3(), AudioChannelSet::createFront7point0(), AudioChannelSet::createFront7point1(), AudioChannelSet::createLCR(), AudioChannelSet::createLCRS(), AudioChannelSet::createLRS(), AudioChannelSet::disabled(), AudioChannelSet::hexagonal(), AudioChannelSet::mono(), AudioChannelSet::octagonal(), AudioChannelSet::pentagonal(), AudioChannelSet::quadraphonic(), and AudioChannelSet::stereo().
Referenced by auChannelIndexToJuce(), and juceChannelIndexToAu().
static int AudioUnitHelpers::auChannelIndexToJuce (int auIndex, const AudioChannelSet & channelSet) static
References AudioUnitHelpers::AUChannelStreamOrder::auLayoutTag, ChannelSetToCALayoutTag(), CoreAudioChannelLabelToJuceType(), AudioChannelSet::getChannelTypes(), AudioChannelSet::hexagonal(), jassert, AudioChannelSet::leftRearSurround, AudioChannelSet::leftSurround, AudioChannelSet::pentagonal(), AudioChannelSet::rightRearSurround, AudioChannelSet::rightSurround, and AudioUnitHelpers::AUChannelStreamOrder::speakerOrder.
static int AudioUnitHelpers::juceChannelIndexToAu (int juceIndex, const AudioChannelSet & channelSet) static
References AudioUnitHelpers::AUChannelStreamOrder::auLayoutTag, ChannelSetToCALayoutTag(), CoreAudioChannelLabelToJuceType(), AudioChannelSet::getTypeOfChannel(), AudioChannelSet::hexagonal(), jassertfalse, AudioChannelSet::leftRearSurround, AudioChannelSet::leftSurround, AudioChannelSet::pentagonal(), AudioChannelSet::rightRearSurround, AudioChannelSet::rightSurround, and AudioUnitHelpers::AUChannelStreamOrder::speakerOrder.
Referenced by AudioUnitHelpers::ChannelRemapper::get().
static bool AudioUnitHelpers::isAudioBufferInterleaved (const AudioBufferList & audioBuffer) static noexcept
Referenced by copyAudioBuffer(), AudioUnitHelpers::CoreAudioBufferList::pop(), and AudioUnitHelpers::CoreAudioBufferList::push().
static void AudioUnitHelpers::clearAudioBuffer (const AudioBufferList & audioBuffer) static noexcept
References zeromem().
static void AudioUnitHelpers::copyAudioBuffer (const AudioBufferList & audioBuffer, const int channel, const UInt32 size, float * dst) static noexcept
References isAudioBufferInterleaved(), and jassert.
Referenced by AudioUnitHelpers::CoreAudioBufferList::pop(), and AudioUnitHelpers::CoreAudioBufferList::push().
static void AudioUnitHelpers::copyAudioBuffer (const float * src, const int channel, const UInt32 size, AudioBufferList & audioBuffer) static noexcept
References isAudioBufferInterleaved(), and jassert.
static Array<AUChannelInfo> AudioUnitHelpers::getAUChannelInfo (PluginBusUtilities & busUtils) static
References SortedSet< ElementType, TypeOfCriticalSectionToUse >::add(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), auChannelStreamOrder, AudioProcessor::busArrangement, SortedSet< ElementType, TypeOfCriticalSectionToUse >::contains(), PluginBusUtilities::getDefaultLayoutForChannelNumAndBus(), PluginBusUtilities::getNumChannels(), PluginBusUtilities::getNumEnabledBuses(), AudioProcessor::AudioBusArrangement::inputBuses, AudioChannelSet::isDisabled(), AudioProcessor::AudioBusArrangement::outputBuses, PluginBusUtilities::processor, AudioProcessor::setPreferredBusArrangement(), SortedSet< ElementType, TypeOfCriticalSectionToUse >::size(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Member Data Documentation
AudioUnitHelpers::AUChannelStreamOrder AudioUnitHelpers::auChannelStreamOrder static
Initial value:
=
{
    {kAudioChannelLayoutTag_Mono,               {kAudioChannelLabel_Center, 0, 0, 0, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_Stereo,             {kAudioChannelLabel_Left, kAudioChannelLabel_Right, 0, 0, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_StereoHeadphones,   {kAudioChannelLabel_HeadphonesLeft, kAudioChannelLabel_HeadphonesRight, 0, 0, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_Binaural,           {kAudioChannelLabel_Left, kAudioChannelLabel_Right, 0, 0, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_Quadraphonic,       {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_Pentagonal,         {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_Center, 0, 0, 0}},
    {kAudioChannelLayoutTag_Hexagonal,          {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_Center, kAudioChannelLabel_CenterSurround, 0, 0}},
    {kAudioChannelLayoutTag_Octagonal,          {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_Center, kAudioChannelLabel_CenterSurround, kAudioChannelLabel_LeftWide, kAudioChannelLabel_RightWide}},
    {kAudioChannelLayoutTag_Ambisonic_B_Format, {kAudioChannelLabel_Ambisonic_W, kAudioChannelLabel_Ambisonic_X, kAudioChannelLabel_Ambisonic_Y, kAudioChannelLabel_Ambisonic_Z, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_MPEG_5_0_B,         {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_Center, 0, 0, 0}},
    {kAudioChannelLayoutTag_MPEG_5_1_A,         {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_Center, kAudioChannelLabel_LFEScreen, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, 0, 0}},
    {kAudioChannelLayoutTag_AudioUnit_6_0,      {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_Center, kAudioChannelLabel_CenterSurround, 0, 0}},
    {kAudioChannelLayoutTag_DTS_6_0_A,          {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_RearSurroundLeft, kAudioChannelLabel_RearSurroundRight, 0, 0}},
    {kAudioChannelLayoutTag_MPEG_6_1_A,         {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_Center, kAudioChannelLabel_LFEScreen, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_CenterSurround, 0}},
    {kAudioChannelLayoutTag_AudioUnit_7_0,      {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_Center, kAudioChannelLabel_RearSurroundLeft, kAudioChannelLabel_RearSurroundRight, 0}},
    {kAudioChannelLayoutTag_MPEG_7_1_C,         {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_Center, kAudioChannelLabel_LFEScreen, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_RearSurroundLeft, kAudioChannelLabel_RearSurroundRight}},
    {kAudioChannelLayoutTag_AudioUnit_7_0_Front,{kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_Center, kAudioChannelLabel_LeftCenter, kAudioChannelLabel_RightCenter, 0}},
    {kAudioChannelLayoutTag_AudioUnit_7_1_Front,{kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_Center, kAudioChannelLabel_LFEScreen, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_LeftCenter, kAudioChannelLabel_RightCenter}},
    {kAudioChannelLayoutTag_MPEG_3_0_A,         {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_Center, 0, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_MPEG_3_0_B,         {kAudioChannelLabel_Center, kAudioChannelLabel_Left, kAudioChannelLabel_Right, 0, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_MPEG_4_0_A,         {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_Center, kAudioChannelLabel_CenterSurround, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_MPEG_4_0_B,         {kAudioChannelLabel_Center, kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_CenterSurround, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_ITU_2_1,            {kAudioChannelLabel_Left, kAudioChannelLabel_Right, kAudioChannelLabel_CenterSurround, 0, 0, 0, 0, 0}},
    {kAudioChannelLayoutTag_EAC3_7_1_C,         {kAudioChannelLabel_Left, kAudioChannelLabel_Center, kAudioChannelLabel_Right, kAudioChannelLabel_LeftSurround, kAudioChannelLabel_RightSurround, kAudioChannelLabel_LFEScreen, kAudioChannelLabel_LeftSurroundDirect, kAudioChannelLabel_RightSurroundDirect}},
    {0,                                         {0,0,0,0,0,0,0,0}}
}
Referenced by getAUChannelInfo().
The documentation for this struct was generated from the following file:
juce_AU_Shared.h